### ISSUE TITLE
Which FlowSOM github is the official one ?

### ISSUE THREAD

**Issue by gitdemont** [saeyslab/FlowSOM#12]
Hi,

I would like to report an issue and I am wondering if I should do it on [@sayeslab](https://github.com/saeyslab/FlowSOM/) or on [@SofieVG](https://github.com/SofieVG/FlowSOM/)

**Comment by SofieVG** [comment]
The @saeyslab github is the one currently in use where several people are
developing, so this one will have the most recent version, and I would
recommend you to report your issue there.
Apologies for this unclear setup, we try to keep the @SofieVG one up to
date as well as this one is referred to in the publication.

**Comment by gitdemont** [comment]
Thanks
