### ISSUE TITLE
Errors in new versions of ReadInput and BuildSOM

### ISSUE THREAD

**Issue by lmweber** [saeyslab/FlowSOM#5]
Hi, I am working through some Bioconductor build errors for my package [diffcyt](https://github.com/lmweber/diffcyt) before the upcoming Bioconductor release date, and I have traced a couple of them to recent updates in `FlowSOM`.

There are two issues, which result in errors in the build report for the `diffcyt` vignette in [Bioc-devel](http://bioconductor.org/packages/devel/bioc/html/diffcyt.html).

The first one was in the print method for `ReadInput()`, which you can see also if you run the following code from the `FlowSOM` vignette. (I emailed @SofieVG about this one yesterday, and I think it has already been resolved - sorry, I should have put this into a GitHub issue instead of an email!)

```
fileName <- system.file("extdata", "68983.fcs", package = "FlowSOM")
fSOM <- ReadInput(fileName, compensate = TRUE, transform = TRUE, 
                    toTransform = c(8:18), scale = TRUE)
str(fSOM)
```

The second issue is due to the `colsToUse` argument for `BuildSOM()`. Previously in my examples, I provided `colsToUse` as a logical vector. However it now no longer accepts logical, so I get an error if I run code like the following with `colsToUse` as logical:

```
> fsom <- ReadInput(d_ff, transform = FALSE, scale = FALSE)
> fsom <- BuildSOM(fsom, colsToUse = colsToUse)
Building SOM

Error in GetChannels(fsom, colsToUse) : 
  Marker ^\QFALSE\E$ could not be found
```

Would it be possible to change this to accept logical again for the `colsToUse` argument? E.g. it could be fixed with an internal check in `BuildSOM` that converts logical to indices, such as: `if (is.logical(colsToUse)) colsToUse <- which(colsToUse)`

**Comment by SofieVG** [comment]
Hi Lukas,

Both of these issues should be resolved with the latest commits.
Let us know if you encounter any other issues, we indeed updated quite a bit (also switched to ggplot for graphics etc).

All the best,
Sofie
